### ISSUE TITLE
Bug in calculating the 2D descriptors

### ISSUE THREAD

**Issue by xiaoboy185** [bobbypaton/DBSTEP#28]
When excute the following command line:
python -m dbstep examples/smiles.txt --2d --fg "C(O)=O" --maxpath 5 --2d-type mcgowan
the error appears:
Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DELL\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DELL\anaconda3\lib\site-packages\dbstep\__main__.py", line 17, in <module>
    sys.exit(Dbstep.main())
  File "C:\Users\DELL\anaconda3\lib\site-packages\dbstep\Dbstep.py", line 531, in main
    vec_df = graph.mol_to_vec(file,options.shared_fg,options.voltype,options.max_path_length,options.verbose)
  File "C:\Users\DELL\anaconda3\lib\site-packages\dbstep\graph.py", line 106, in mol_to_vec
    mol,prop = make_mol_obj(line)
  File "C:\Users\DELL\anaconda3\lib\site-packages\dbstep\graph.py", line 75, in make_mol_obj
    return mol,prop
UnboundLocalError: local variable 'prop' referenced before assignment

**Comment by xiaoboy185** [comment]
When do the pip install dbstep, the 1.1.0 version of dbstep is install, which will give the above error message.
To intall the lastest version 1.2a.0, the error fixed

**Comment by luchini18** [comment]
Hi, 
Sorry for the delay, I checked this out and it turns out it's a valid bug. technically the 1.2a.0 install is older than the 1.1.0 version, sorry for the confusion in versions there. The changes have been made on github and we will update a version for pip/conda soon! 
Thanks for catching this!
